export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpg",
    username: "Halil İbrahim Akca",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Ethan Diaz",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Neo Graves",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Elif Kirby",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Alvin Gonzales",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Julian Wilcox",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Hasnain Lowe",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Nevaeh Stone",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Alia Stuart",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Lori Lewis",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    userId: 1,
    date: "5 mins ago",
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Exploring new places and making memories.",
    photo: "assets/post/2.jpeg",
    userId: 2,
    date: "15 mins ago",
    like: 45,
    comment: 12,
  },
  {
    id: 3,
    desc: "Sunsets and palm trees 🌅🌴",
    photo: "assets/post/3.jpeg",
    userId: 3,
    date: "1 hour ago",
    like: 67,
    comment: 18,
  },
  {
    id: 4,
    desc: "Coffee and conversations.",
    photo: "assets/post/4.jpeg",
    userId: 4,
    date: "2 hours ago",
    like: 23,
    comment: 6,
  },
  {
    id: 5,
    desc: "Lost in the beauty of nature.",
    photo: "assets/post/5.jpeg",
    userId: 5,
    date: "3 hours ago",
    like: 78,
    comment: 21,
  },
  {
    id: 6,
    desc: "Chasing dreams and catching sunsets.",
    photo: "assets/post/6.jpeg",
    userId: 6,
    date: "4 hours ago",
    like: 56,
    comment: 15,
  },
  {
    id: 7,
    desc: "Adventures with friends are the best!",
    photo: "assets/post/7.jpeg",
    userId: 7,
    date: "5 hours ago",
    like: 43,
    comment: 11,
  },
  {
    id: 8,
    desc: "City lights and late nights.",
    photo: "assets/post/8.jpeg",
    userId: 8,
    date: "6 hours ago",
    like: 34,
    comment: 8,
  },
  {
    id: 9,
    desc: "Embracing the journey, one step at a time.",
    photo: "assets/post/9.jpeg",
    userId: 9,
    date: "7 hours ago",
    like: 65,
    comment: 17,
  },
  {
    id: 10,
    desc: "Inspiration is all around us.",
    photo: "assets/post/10.jpeg",
    userId: 10,
    date: "8 hours ago",
    like: 50,
    comment: 13,
  },
];
